CREATE TABLE IF NOT EXISTS TEMP_MERGE_PANEL AS
SELECT ASHARE_DAILY_PANEL.ts_code,
       ASHARE_DAILY_PANEL.trade_date,
       ASHARE_DAILY_PANEL.pct_chg,
       ASHARE_BASIC_PANEL.total_mv
FROM FIN_PANEL_DATA.ASHARE_DAILY_PANEL
         LEFT JOIN
     FIN_PANEL_DATA.ASHARE_BASIC_PANEL
     ON
                 ASHARE_DAILY_PANEL.ts_code = ASHARE_BASIC_PANEL.ts_code AND
                 ASHARE_DAILY_PANEL.trade_date = ASHARE_BASIC_PANEL.trade_date
WHERE ASHARE_DAILY_PANEL.trade_date >= 20140101;

